API provides ability for registered user to bid
CraftAcademy/bidspace-api-june-2020 pull request #11
Opened 2020-09-04 14:46 UTC by Odeane

## [PT board URL]( https://www.pivotaltracker.com/story/show/174562909)
### User Story
```
As a registered user
in order to rent a space from the landlord
I would like to be able to bid on listings
```
## Changes proposed in this pull request:
* Registered user can bid

2020-09-04 16:07 UTC, Alex-Bellamy approved these changes

2020-09-07 08:27 UTC, oliverochman requested changes

2020-09-07 08:27 UTC, oliverochman commented on spec/factories/biddings.rb
> +    listing_id {65}
please refactor to `association :listing`

2020-09-07 08:27 UTC, oliverochman commented on spec/requests/api/v1/bidding/biddings_request_spec.rb
> +  let!(:user) { create(:user, role: 'registered') }
please correct the indentation in this file

2020-09-07 08:27 UTC, oliverochman commented on app/controllers/api/v1/biddings_controller.rb
> +    if bidding.persisted?
please correct the indentation in this file

2020-09-07 08:31 UTC, oliverochman requested changes

2020-09-07 08:31 UTC, oliverochman commented on app/models/bidding.rb
> +  belongs_to :user
Add a `before_create` hook here where you check if the current user that is submitting the bid is the same as the landlord of the listing that he wants to bid on. If that is the case raise an error.

2020-09-07 08:32 UTC, oliverochman commented on app/models/bidding.rb
> +  belongs_to :user
Also add a test for this

2020-09-07 12:49 UTC, oliverochman approved these changes
Good job guys!

2020-09-07 12:49 UTC, merged