Api provides the ability to get a specific rental space
CraftAcademy/bidspace-api-june-2020 pull request #4
Opened 2020-08-31 18:55 UTC by Odeane

## [PT board URL](https://www.pivotaltracker.com/story/show/174549367)
### User Story
```
As a api
in order for client to request specific space
i would like to be able to provide an endpoint for showing a space.
```
## Changes proposed in this pull request:
* Adding show action
Add show action to route

2020-08-31 19:08 UTC, Alex-Bellamy approved these changes

2020-08-31 19:10 UTC, viktorsommar requested changes

2020-08-31 19:10 UTC, viktorsommar commented on app/models/listing.rb
> +  validates_presence_of :category, :lead, :scene, :height, :description, :price
Should be "dimensions" instead of just "height". You might have different kind of spaces were the dimensions would be important

2020-08-31 19:10 UTC, viktorsommar commented on app/serializers/listing_show_serializer.rb
> +  attributes :id, :category, :lead, :scene, :description, :height, :price
Same here with dimensions

2020-08-31 19:59 UTC, viktorsommar approved these changes

2020-09-01 07:14 UTC, felixoppongwillborg approved these changes

2020-09-01 07:14 UTC, merged